export enum CustomEvents {
  WALLET_CONNECT_SUCCESS = "WALLET_CONNECT_SUCCESS",
  WALLET_CONNECT_ABORTED = "WALLET_CONNECT_ABORTED",
  WALLET_CONNECT_FAILED = "WALLET_CONNECT_FAILED",
  WALLET_CONNECT_MODAL_CLOSED = "WALLET_CONNECT_MODAL_CLOSED",
  WALLET_CONNECT_MODAL_OPENED = "WALLET_CONNECT_MODAL_OPENED",
}

export enum WalletProvider {
  NONE = "NONE",
  UNISAT = "UNISAT",
  XVERSE = "XVERSE",
  LEATHER = "LEATHER",
  OKX = "OKX",
}

export enum Errors {
  "WALLET_EXTENSION_NOT_FOUND" = "WALLET_EXTENSION_NOT_FOUND",
  "WALLET_CONNECTION_REQUEST_ERROR" = "WALLET_CONNECTION_REQUEST_ERROR",
}
